{"name": "test_div[division by zero]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'division by zero' == 'divsion by zero'\n  - divsion by zero\n  + division by zero\n  ?    +", "trace": "self = <testing.test_calculator.TestCalculator object at 0x040212B0>, c = 100, d = 0, divexpect = 1\n\n    @allure.story(\"除法运算测试\")\n    @pytest.mark.parametrize('c,d,divexpect', get_divdatas_calc()[0], ids=get_divdatas_calc()[1])\n    @pytest.mark.div\n    \n    def test_div(self, c, d, divexpect):\n        try:\n        # calc = calculator()\n        # assert 1 == self.calc.div(1, 1)\n>        res = self.calc.div(c, d)\n\ntesting\\test_calculator.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pythoncode.calculator.calculator object at 0x04021DA8>, a = 100, b = 0\n\n    def div(self, a, b):\n>       return a / b\nE       ZeroDivisionError: division by zero\n\npythoncode\\calculator.py:9: ZeroDivisionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testing.test_calculator.TestCalculator object at 0x040212B0>, c = 100, d = 0, divexpect = 1\n\n    @allure.story(\"除法运算测试\")\n    @pytest.mark.parametrize('c,d,divexpect', get_divdatas_calc()[0], ids=get_divdatas_calc()[1])\n    @pytest.mark.div\n    \n    def test_div(self, c, d, divexpect):\n        try:\n        # calc = calculator()\n        # assert 1 == self.calc.div(1, 1)\n         res = self.calc.div(c, d)\n        except Exception as e:\n         print(\"发生异常，异常信息{}，进行异常断言\".format(e))\n>        assert str(e) == 'divsion by zero'\nE        AssertionError: assert 'division by zero' == 'divsion by zero'\nE          - divsion by zero\nE          + division by zero\nE          ?    +\n\ntesting\\test_calculator.py:56: AssertionError"}, "parameters": [{"name": "c", "value": "100"}, {"name": "d", "value": "0"}, {"name": "divexpect", "value": "1"}], "start": 1624034897051, "stop": 1624034897055, "uuid": "09f69d57-e10e-48d9-aa6e-9aa72f2c28df", "historyId": "bc843015088da1ff336f67fce66c9af3", "testCaseId": "00f43c99e69edabe02f02364c544f882", "fullName": "test_calculator.TestCalculator#test_div", "labels": [{"name": "story", "value": "除法运算测试"}, {"name": "feature", "value": "加法和除法测试"}, {"name": "tag", "value": "div"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "QKFZ-888"}, {"name": "thread", "value": "9628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}