{"name": "除法运算-异常:100/0", "status": "passed", "steps": [{"name": "2. 除数不能为0的异常处理", "status": "passed", "start": 1624428042145, "stop": 1624428042145}], "attachments": [{"name": "log", "source": "8c690d36-f8fc-4e8a-b14d-84da871ed380-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "0"}, {"name": "expect", "value": "1"}], "start": 1624428042143, "stop": 1624428042145, "uuid": "e5f21a72-7f19-4b0a-958a-3c01371e725c", "historyId": "f9dcfaa5ba67a0f2050567b2685e2e50", "testCaseId": "86bdf1d3b5df90ee666d9c0184f304cf", "fullName": "test_calculator.TestCalculator#test_div_Error", "labels": [{"name": "feature", "value": "加法和除法运算"}, {"name": "story", "value": "除法运算-异常处理"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "QKFZ-888"}, {"name": "thread", "value": "8080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}